apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-k8s-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-k8s-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-k8s-test
    spec:
      containers:
      - name: gke-k8s-test
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m