name: Pylint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - develop
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f ./app/requirements.txt ]; then pip install -r ./app/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=2.0 ./app/`ls -R|grep .py$|xargs`
    - name: Running tests with pytest
      run: |
        cd app
        python -m pytest
